### ISSUE TITLE
DNA Lab: Generate & Add GTAC IDs to new entities

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#181]
Will need to implement this at every entry point in the workflow chain and on every sample protocol.

See 'record_service_request' or 'create_dilutions' YAMLs for examples.

**Comment by tim-snyder-wustl** [comment]
Example:

```
'SEQ Lab: Receive Library':
  desc: Review project details
  meta:
    augment: {}
    blocks: []
    initialContextFunction: ''
    name: report
    protocol_actions:
      - conditions:
          - andOr: and
            condition: All rows completed
            parameters: {}
        consequences:
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Sample Name
              target: Sample Name
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: GTAC ID
              target: GTAC_ID                 
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Funding Source
              target: Funding Source          
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Assessed Molarity (nM)
              target: Assessed Molarity (nM)         
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Average Library Size (bp)
              target: Average Library Size (bp)              
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Remaining Volume (Âµl)
              target: Remaining Volume (Âµl)          
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: i7 Index Sequence
              target: i7 Index Sequence          
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: i5 Index Sequence
              target: i5 Index Sequence          
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Drop Off Date
              target: Drop Off Date          
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Billing PI
              target: Billing PI
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Flow Cell Type
              target: Flow Cell Type
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Flow Cell Cycles
              target: Flow Cell Cycles
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Flow Cell Workflow
              target: Flow Cell Workflow
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Sequencing Recipe
              target: Sequencing Recipe
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Requested Amount of Flow Cell
              target: Requested Amount of Flow Cell
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Requested Number of Reads (M)
              target: Requested Number of Reads (M)
          - consequence: Synchronize Field Value to Entity
            parameters:
              source: Library Type
              target: Library Type
        description: Desc 0
        id: 0
        name: Sync Library and Pool Data
    report:
      blocks: []
      initialContextFunction: ''
      userParameters: []
    userParameters: []
  protocol: standard
  tags:
    - seq
  variables:
    - Project Name:
        onchange: "onchange_autofill(api, 'Project Name', newValue)"
        read_only: true
        rule: text
        value: '{{ project_name() }}'
    - GTAC Seq:
        read_only: true
        rule: text
        tags:
          - esp:gtac_seq
        value: '{{ "{:012d}".format(int(hid_for_uuid(sample["uuid"], "gtac_seq"))) }}'
        visible: false
    - Sample Type:
        read_only: true
        rule: text
        value: '{{ entity_type_name() }}'
        visible: false        
    - Suffix:
        read_only: true
        rule: text
        value: "{{ { 'Specimen': 'E', 'Lysate': 'Y', 'RNA': 'R', 'cDNA': 'C', 'mRNA': 'M', 'Illumina Library': 'L',\
          \ 'Illumina Library Pool': 'S' }.get(cell('Sample Type')) }}"
        visible: false        
    - GTAC ID:
        augment:
          renderer: IdentifierSplitRenderer
        read_only: true
        rule: text
        value: "{{ (cell('GTAC Seq') + cell('Suffix')) if entity_value('GTAC_ID') is None else entity_value('GTAC_ID') }}"        
        tags:
          - esp:gtac_id
    - Sample Name:
        required: true
        rule: text
        value: "{{ entity_value('Sample Name') }}"
    - Barcode:
        barcode_type: QR
        read_only: true
        resource_barcode: true
        rule: barcode
        value: "{{ '+'.join([cell('GTAC ID'), sample_type_name()]) }}"
        visible: true
    - Funding Source:
        onchange: "onchange_autofill(api, 'Funding Source', newValue)"
        required: true
        rule: text
        value: "{{ entity_value('Funding Source') or '' }}"
    - Assessed Molarity (nM):
        required: true
        rule: text
        value: "{{ entity_value('Assessed Molarity (nM)') }}"
    - "Average Library Size (bp)":
        required: true
        rule: text
        value: "{{ entity_value('Average Library Size (bp)') }}"
    - "Remaining Volume (Âµl)":
        required: true
        rule: text
        value: "{{ entity_value('Remaining Volume (Âµl)') }}"
    - Combined Index Sequence (i7-i5):
        required: true
        rule: text
        value: "{{ entity_value('i7 Index Sequence') + '-' + entity_value('i5 Index Sequence') }}"
    - i7 Index Sequence:
        required: true
        rule: text
        value: "{{ entity_value('i7 Index Sequence') }}"
    - i5 Index Sequence:
        required: true
        rule: text
        value: "{{ entity_value('i5 Index Sequence') }}"
    - Drop Off Date:
        format: DD-MM-YYYY
        required: true
        rule: date
        value: "{{ entity_value('Drop Off Date') }}"
    - Cost Center ID:
        onchange: "onchange_autofill(api, 'Cost Center ID', newValue)"
        required: true
        rule: text
    - Billing PI:
        onchange: "onchange_autofill(api, 'Billing PI', newValue)"
        required: true
        rule: text
        value: "{{ entity_value('Billing PI') }}"
    - Flow Cell Type:
        required: true
        rule: text
        value: "{{ entity_value('Flow Cell Type') }}"
    - Flow Cell Cycles:
        required: true
        rule: text
        value: "{{ entity_value('Flow Cell Cycles') }}"
    - Flow Cell Workflow:
        required: true
        rule: text
        value: "{{ entity_value('Flow Cell Workflow') }}"
    - Sequencing Recipe:
        required: true
        rule: text
        value: "{{ entity_value('Sequencing Recipe') }}"
    - Requested Amount of Flow Cell:
        required: true
        rule: text
        value: "{{ entity_value('Requested Amount of Flow Cell') }}"
    - Requested Number of Reads (M):
        required: true
        rule: text
        value: "{{ entity_value('Requested Number of Reads (M)') }}"
    - Library Type:
        required: true
        rule: text
        value: "{{ entity_value('Library Type') }}"
    - Next Step:
        dropdown: '{{ next_node_choices_ht() }}'
        onchange: "onchange_autofill(api, 'Next Step', newValue)"
        required: true
        rule: dropdown
        value: ''
```
